#!/bin/bash

# Takes in the image to be processed
# 1. The image to be processed

# Check that the correct number of parameters were passed
if [ $# -ne 1 ]; then
    echo "Usage: $0 <image>"
    exit 1
fi

# Run the matlab script
matlab -nojvm -nodesktop -r "main('$1'); exit;"